### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by zabbal** [shkolnick-kun/bugurtos#10]
Having couple of example apps to be used with BugurtOS would certainly come in handy alongside with corresponding documentation.

**Comment by shkolnick-kun** [comment]
Can you read russian?

**Comment by shkolnick-kun** [comment]
Actuallly you can use test projects as examples, or you can ask questions here.

**Comment by shkolnick-kun** [comment]
Hi !

What kind of documentation do you need?
Doxygen docs are already in place, check releases.

If you need something like "Getting started with BuguRTOS", then you can
ask questions or wait for translation of russian "noobs guide".
But actually I must first edit russian "noobs guide" for BuguRTOS-0.8.x.

Best regards,
shkolnick-kun.

2015-05-12 19:30 GMT+05:00 zabbal <notifications@github.com>:

**Comment by shkolnick-kun** [comment]
Ok,
Here is [GettingStartedEN](https://github.com/shkolnick-kun/bugurtos/blob/wiki/GettingStartedEN.md).
@zabbal  is welcome to read.
@dartraiden is welcome with his magic spell check.

**Comment by dartraiden** [comment]
Done
https://github.com/shkolnick-kun/bugurtos/pull/11

**Comment by shkolnick-kun** [comment]
Thanks for the help.

**Comment by shkolnick-kun** [comment]
No feedback from @zabbal, /thread.
