### ISSUE TITLE
Port for CM1

### ISSUE THREAD

**Issue by Endag** [shkolnick-kun/bugurtos#28]
Are there any plans for porting to Cortex-M1 core in near time?

**Comment by shkolnick-kun** [comment]
I don't have any hardware for testing Cortex-M1 right now, so I don't think that I should write a port which I could not test!

But I think Cortex-M0 code should work on little endian Cortex-M1 with OS extension, as both cores are ARMv6-M with 3-stage pipeline and have identical (as wikipedia says) command sets.

If your particular core is big-endian, or if id does not have MSP/PSP, then Cortex-M0 port wont work on it.

**Comment by shkolnick-kun** [comment]
And yes! 

If you see [Chibios ARM port header](https://github.com/ChibiOS/ChibiOS/blob/master/os/common/ports/ARMCMx/chcore.h) you'll find that Cortex-M0 and Cortex-M1 cores are supposed to use exactly the same code.

The only question remaining is "Do we have the reason to port BuguRTOS to Cortex-M1 without OS extension?"

I think, I won't do it at the moment.
