### ISSUE TITLE
Synchronization primitives usage

### ISSUE THREAD

**Issue by Endag** [shkolnick-kun/bugurtos#29]
There is somethat unclear in documentation about synchronization primitives (condvars, mutexes, etc.) usage - is it right and safe to call functions like mutex_lock/unlock and cond_signal/broadcast in ISRs (at least in vint handlers).

Can you provide any info about intended usage?

**Comment by shkolnick-kun** [comment]
Hi!
As kernel is almost fully preemptive you shouldn't work with sync primitives in real ISRs, but you can do certain things in vint handlers.

ISR  safe (vint safe actually) things have _isr postfix they should be called from vint handlers.
At the moment only counting semaphores can be used for **process<->vint_handler** communication.

Other native lib primitives are supposed to be used in **process<->process** communications.

Regards.

**Comment by shkolnick-kun** [comment]
Also If you need something, you can request here!
I have a lot of work now, but I'll get some spare time on November 2016.

**Comment by Endag** [comment]
Yes, I noticed that there is a very little of _isr postfixes among native lib functions, and that's why I posted that question in first place, so I think it all should be stated clearly in documentation to avoid any further misunderstanding.

> ISR safe (vint safe actually) things have _isr postfix they should be called from vint handlers.
At the moment only counting semaphores can be used for process<->vint_handler communication.

So it's a bad idea call right in real ISR _sem_free_isr_ and I should use **isr->vint->process** contraption?

**Comment by shkolnick-kun** [comment]
>avoid any further misunderstanding.
Actually mutex and condvar can't be used in non IPC things by definition. These primitives are supposed to be used in processes/threads in any OS with little or no exceptions.

> So it's a bad idea call right in real ISR sem_free_isr and I should use isr->vint->process contraption?
Yes you are right!

> I think it all should be stated clearly in documentation to avoid any further misunderstanding.
I'll do doc clarification in late versions, also I'll consider API change (rename things) to clarify things usage.

**Comment by Endag** [comment]
> Yes you are right!

Actually, i meanwhile tried to use semaphores directly in ISR and so far it forked fine. Could you explain possible implications of doing this way?

> Also If you need something, you can request here!

Based on this discussion I think there is needed a method to wake up waiting thread on hardware events (i.e. from isrs) directly, not through  **isr->vint->process** contraption, because this way is really not clear (FreeRTOS for ex. allows at least to increment semaphore in isr, some other OS allow to post user-defined posix events) and also probably not very good for performance and response time

**Comment by shkolnick-kun** [comment]
> Actually, in meanwhile I tried to use semaphores directly in ISR and so far it forked fine. Could you explain possible complications of doing this way?

This may (and will) lead to race condition between ISR and the kernel thread when ISR preempts kernel thread.

>I think there is needed a method to wake up waiting thread on hardware events (i.e. from isrs) directly

Such direct approach is not possible in a fully preemptive kernel architecture, so there are two solutions for the problem:

1. Change the  architecture to "kernel with preemption points" with dramatic "hot" interrupt latency degradation. So "hot" interrupts which don't use OS functions will have to wait for preemption point in the kernel thread (which may take about 100us on STM8/AVR @ 16MHz).

2. Make some ad hoc mechanism for kernel thread notification. E.g. you can make some flag variable which mus be set in ISR and custom BGRT_KERNEL_PREEMPT/BGRT_CONFIG_SAVE_POWER macros which must analyze flags and notify some processes through semaphores (recomended) or through proc_run_isr calls.

**Comment by Endag** [comment]
> (which may take about 100us on STM8/AVR @ 16MHz).

Curious. I'm right now getting about 300us (up to 500+us) time gap between entering in hw ISR and semaphore acquire in process thread on 24MHz ARM-M0(M1 actually, but no significant differences) (via isr->vint->process route, but direct isr->process gives same result somehow). And this is an RT-thread on priority 0 so I don't know that to do to make it react faster.

Any suggestion to where I should check for performance black holes?

**Comment by shkolnick-kun** [comment]
I'll check it on Cortex-M0 board tomorrow.

**Comment by shkolnick-kun** [comment]
OK. Here is my first result:
STM32F051R8T6 @ 32MHz
```C
/*bugurt_port.c*/
void BGRT_SYSTEM_TIMER_ISR(void)
{
    LED_ON(RED);
    BGRT_ISR_START();

    bgrt_kernel.timer.val++;
    if (bgrt_kernel.timer.tick != (void (*)(void))0)bgrt_kernel.timer.tick();

    BGRT_KBLOCK.tmr_flg = (bgrt_bool_t)1;
    bgrt_vint_push_isr(&BGRT_KBLOCK.int_sched, &BGRT_KBLOCK.vic);

    BGRT_ISR_END();
}
/*kernel.c*/
void bgrt_kblock_main(bgrt_kblock_t * kblock)
{
    while (1)
    {

        bgrt_vic_do_work(&kblock->vic);
        LED_OFF(RED);
        bgrt_switch_to_proc();
    }
}
```
Interrupt service time is 64us/

**Comment by shkolnick-kun** [comment]
```C
/*bugurt_port.c*/
void BGRT_SYSTEM_TIMER_ISR(void)
{
    LED_ON(RED);
    BGRT_ISR_START();

    bgrt_kernel.timer.val++;
    if (bgrt_kernel.timer.tick != (void (*)(void))0)bgrt_kernel.timer.tick();

    BGRT_KBLOCK.tmr_flg = (bgrt_bool_t)1;
    bgrt_vint_push_isr(&BGRT_KBLOCK.int_sched, &BGRT_KBLOCK.vic);

    BGRT_ISR_END();
}
/*test_func.c*/
bgrt_vint_t test_vint;
void systick_hook(void)
{
    //NOP();
    bgrt_vint_push_isr(&test_vint, &BGRT_KBLOCK.vic);
}
/*main.c*/
extern bgrt_vint_t test_vint;
sem_t test_sem2;
void main_sem2(void * arg)
{
    (void)arg;
    while (1)
    {
        sem_lock(&test_sem2);
        LED_OFF(RED);
    }
}
int main(void)
{
    /***************************************************
    *          For test purposes only!!!               *
    *  It is strongly recommended to initiate hardware *
    *         AFTER bgrt_init() call!!!                *
    ***************************************************/
    /*
     * This function disables interrupts
     * and initiates hardware.
     */
    init_hardware();
    bgrt_init();

    sem_init_isr(&test_sem2, 0);
    bgrt_vint_init(&test_vint, 0, (bgrt_code_t)sem_free_isr, (void*)&test_sem2);
    BGRT_SCHED_SYSTICK_HOOK_ADD();

    _bgrt_proc_init(PR0, main_with_return,   SVH0, RSH0, 0, &bgrt_proc_stack[0][BGRT_PROC_STACK_SIZE-1], 1,      1, 0 ARG_END);
    _bgrt_proc_init(PR1, main_lb,            SVH1, RSH1, 0, &bgrt_proc_stack[1][BGRT_PROC_STACK_SIZE-1], LOWEST, 1, 0 BGRT_SCHED_ARG_END);
    _bgrt_proc_init(PR2, main_sem,           SVH2, RSH2, 0, &bgrt_proc_stack[2][BGRT_PROC_STACK_SIZE-1], 2,      2, 0 ARG_END);
    _bgrt_proc_init(PR3, main_sem2,          SVH3, RSH3, 0, &bgrt_proc_stack[2][BGRT_PROC_STACK_SIZE-1], 0,      2, 0 ARG_END);

    sem_init_isr(&test_sem, 1);

    _bgrt_proc_run(PR0);

    bgrt_start();
    return 0;
}
```

200us time is stable, no jitter

**Comment by shkolnick-kun** [comment]
sem_free_isr execution time 20us

**Comment by shkolnick-kun** [comment]
sem_free_isr to LED_OFF delay 150us

**Comment by shkolnick-kun** [comment]
It seems like there is some logical error in syscall dispatcher _bgrt_sync_sleep is called three times per sem_lock call instead of two.

I have to trace it.

**Comment by shkolnick-kun** [comment]
OK.
There are three problems:
1. Lack of robustness in the kernel thread code.
2. Logical error if sem_lock (incorrect code, must be fixed).
3. SLOW sem_lock design.

First of all I'll fix the kernel code to make it more robust to errors in libs. Next I'll fix redesign sem_lock.

**Comment by shkolnick-kun** [comment]
OK, @Endag!
I've fixed both kernel and sem, and redesigned sem_lock.
Please check handling time and give me the feedback.
Regards.

**Comment by Endag** [comment]
Thanks. Will go to test it and report results.

**Comment by shkolnick-kun** [comment]
```C
/*test_func.c*/
bgrt_vint_t test_vint;
void systick_hook(void)
{
    //NOP();
    LED_ON(RED);
    bgrt_vint_push_isr(&test_vint, &BGRT_KBLOCK.vic);
}
/*main.c*/
extern bgrt_vint_t test_vint;
sem_t test_sem2;
void main_sem2(void * arg)
{
    (void)arg;
    while (1)
    {
        sem_lock(&test_sem2);
        LED_OFF(RED);
    }
}


int main(void)
{
    /***************************************************
    *          For test purposes only!!!               *
    *  It is strongly recommended to initiate hardware *
    *         AFTER bgrt_init() call!!!                *
    ***************************************************/
    /*
     * This function disables interrupts
     * and initiates hardware.
     */
    init_hardware();
    bgrt_init();

    sem_init_isr(&test_sem2, 0);
    bgrt_vint_init(&test_vint, 0, (bgrt_code_t)sem_free_isr, (void*)&test_sem2);
    BGRT_SCHED_SYSTICK_HOOK_ADD();

    _bgrt_proc_init(PR0, main_with_return,   SVH0, RSH0, 0, &bgrt_proc_stack[0][BGRT_PROC_STACK_SIZE-1], 1,      1, 0 ARG_END);
    _bgrt_proc_init(PR1, main_lb,            SVH1, RSH1, 0, &bgrt_proc_stack[1][BGRT_PROC_STACK_SIZE-1], LOWEST, 1, 0 BGRT_SCHED_ARG_END);
    _bgrt_proc_init(PR2, main_sem,           SVH2, RSH2, 0, &bgrt_proc_stack[2][BGRT_PROC_STACK_SIZE-1], 2,      2, 0 ARG_END);
    _bgrt_proc_init(PR3, main_sem2,          SVH3, RSH3, 0, &bgrt_proc_stack[3][BGRT_PROC_STACK_SIZE-1], 0,      2, 0 ARG_END);

    sem_init_isr(&test_sem, 1);

    _bgrt_proc_run(PR0);
    _bgrt_proc_run(PR3);

    bgrt_start();
    return 0;
}
```
STM32F051R8T6 @ 32MHz execution time is 180us

**Comment by Endag** [comment]
```
bgrt_proc_t ptest1;
bgrt_stack_t *test1_stack;

sem_t sem1;
bgrt_vint_t vint1;

void test1(void* arg) {
	while (1) {
		sem_lock(&sem1);
		MDR_PORTA->RXTX |= PORT_Pin_3;
	}
}

void systick_hook() {
	MDR_PORTA->RXTX &= ~PORT_Pin_3;
	bgrt_vint_push_isr(&vint1, &BGRT_KBLOCK.vic);
}

void bg_main(void * arg) {
	LED_INIT();

	LED_OFF();

	test1_stack = malloc(64);

	sem_init(&sem1, 0, 0);

	bgrt_vint_init(&vint1, 0, (bgrt_code_t) sem_free_isr, (void*) &sem1);

	bgrt_proc_init(&ptest1, test1, NULL, NULL, NULL, &test1_stack[255], 1, 5,
			0);

	BGRT_CRIT_SEC_ENTER();
	bgrt_kernel.timer.tick = systick_hook;
	BGRT_CRIT_SEC_EXIT();

	bgrt_proc_run(&ptest1);
}
```

Sightly less than 288us @24MHz - practically same MHz/Time ratio so I think this is all speed that you can get on this CPU. 
 I'll continue to use bgRTOS on pilot project and giving further questions & feedback. This one may be closed I think.
Thanks and regards.

**Comment by shkolnick-kun** [comment]
@Endag I see a logcal error in sem_free, so I'll update it.
