### ISSUE TITLE
Add asynchronous notification mechanism to BuguRTOS.

### ISSUE THREAD

**Issue by shkolnick-kun** [shkolnick-kun/bugurtos#33]
Cast @Endag,  @spth!

I've profiled current BuguRTOS version and I think that virtual interrupts are quite slow at least for frequently called kernel code:
bgrt_vint_push may take up to 5us, and bgrt_vint_pop may take up to 7us on Cortex-M0 @ 32MHz.

In case of AVR/STM8 these times must be even worse as these CPUs don't have clz/ffs instructions!

At the moment syscall and scheduler services use virtual interrupts heavily, thus hitting system performance (in case of sem_free call vint_push/pop may take up to 50us on Cortex-M0 @ 32MHz).

So I suggest adding simpler asynchronous nonblocking mechanism to BuguRTOS for heavy duty kernel work and ligth IPC.

What do you think guys?

**Comment by Endag** [comment]
At glance I can suggest modify vInts with simpler than xList (thus faster) linked list for events, because I don't think for example that priority is really necessary because we should process events quicker than get any real backlog of them (and they still be processed in one burst in kernel thread, so we just may loose time on priority sorting).
I'll try to come up with more ideas during weekend.

**Comment by shkolnick-kun** [comment]
Actually I want to add bitmap notification which is even simpler.
I'll have to add it anyway, because I want to add CMSIS/RTOS library some day.

**Comment by shkolnick-kun** [comment]
OK, I've added simple bitmap based notifications.
Now sem_free takes 140us on Cortex-M0 @ 32MHz.
Please @Endag test it!

**Comment by shkolnick-kun** [comment]
I also found that adding LED_ON/OFF (gpio_set/clear call) to bgrt_disable_interrupts/bgrt_anable_interrupts takes about 20us per sem_free call, so I want to replace them by macros/inline functions.

Also, I can make BGRT_ISR preemptive on Cortex-Mx by not-disabling-interrupts and adding macros such as BGRT_VINT_PUSH_ISR, to call bgrt_vint_push on Cortex-Mx and bgrt_vint_push_isr on AVR/STM8.

**Comment by shkolnick-kun** [comment]
This week I have a lot of work, so I can't get much time for BuguRTOS if You need something, post here.

**Comment by shkolnick-kun** [comment]
OK, replaced bgrt_disable/enable_interrupts with assembler/intrinsics.
Now sem_free takes 122us on Cortex-M0 @ 32MHz when virtual interrupt controller is used.

**Comment by shkolnick-kun** [comment]
Inlined bgrt_fic_*** functions.
Now sem_free takes 122us on Cortex-M0 @ 32MHz 97us without virtual interrupts.

**Comment by shkolnick-kun** [comment]
I think this is the limit for performance optimization, because there is no more "hot" kernel code to optimize.

The only thing remaining are preemptible BGRT_ISR handlers.

Cast @Endag!
