### ISSUE TITLE
Next release.

### ISSUE THREAD

**Issue by shkolnick-kun** [shkolnick-kun/bugurtos#38]
Hi, @dartraiden !

BuguRTOS-4.0.0 release is on the way!

Could you help me with grammar please?

Thanks in advance.

**Comment by dartraiden** [comment]
`WEAK bgrt_cpuid_t bgrt_sched_highest_load_core(bgrt_ls_t * stat) /* ADLINT:SL:[W0432] Intendation*/`

Did you mean _Indentation_?

**Comment by dartraiden** [comment]
[Done](https://github.com/shkolnick-kun/bugurtos/pull/39)

**Comment by shkolnick-kun** [comment]
Cool!
