### ISSUE TITLE
Supported Hardware boards compatibility list?

### ISSUE THREAD

**Issue by informer2016** [shkolnick-kun/bugurtos#40]
@shkolnick-kun it would be nice if there will be a list of Supported Hardware boards, something similar to opensource coreboot BIOS list _(https://www.coreboot.org/status/board-status.html)_  or to LibreCMC opensource/free software blobless WiFi router firmware _(https://gogs.librecmc.org/libreCMC/libreCMC/src/v1.4/docs/Supported_Hardware.md)_

I mean a list of specific boards, which are available for purchase for cheap - e.g. from AliExpress. So that anyone would be able to get such a board, easily configure & install BuguRTOS there _(a few README's on this topic would be nice)_ - and maybe that will attract popularity and new contributors to your project

**Comment by shkolnick-kun** [comment]
Hi, @informer2016!

BuguRTOS is software library, that can be used on any supported uC family, see [Readme.md](https://github.com/shkolnick-kun/bugurtos/blob/master/README.md) and [doc/GettingStarted.md](https://github.com/shkolnick-kun/bugurtos/blob/master/doc/GettingStartedEN.md).

If you are asking for ready to bild firmware, then you can start with [BuguRTOS tests](https://github.com/shkolnick-kun/bugurtos/tree/master/tests/arch).

Before any BuguRTOS release I run tests on all supported uC family. Here is the list of ports which are supported by free tollchains and test hardware:
* AVR/GCC                 - Arduino(tm)-nano (Atmega328p);
* STM8L/SDCC          - STM8L Discovery kit;
* Cortex(tm)-M0/GCC - STM32L051 Discovery kit;
* Cortex(tm)-M3/GCC - STM32L1 Discovery kit for SMT32L152;
* Cortex(tm)-M4/GCC - STM32F4 Discovery kit for SMT32F407;
* Cortex(tm)-M7/GCC - STM32 Nucleo-144 for STM32F767 hihg performance MCUs.

Test projects can be built on Linux with correspondent toolchain and Code::Blocks IDE except STM8L/SDCC which is built on Microsoft(R) Windows(tm).

**Comment by informer2016** [comment]
@shkolnick-kun Thank you very much! So if I buy something [like this board with STM32F767](https://www.aliexpress.com/item/1pcs-STM32F767-development-board-Cortex-M7-small-system-board-STM32F767IGT6-STM32-development-board-Hbm0087/32894489746.html) - which seems to be the most powerful CPU supported by BuguRTOS - it will be compatible?

**Comment by shkolnick-kun** [comment]
It was tested on STM32F767ZI which has exact the same Cortex-M7 core as STM32F767IG. 

To run it on STM32F767IG you can take some test project as a starting point and cut all the code used to blink leds on Nucleo boards.

You may also need to change PLL settings at startup and to adjust BuguRTOS config according to your Hardware config and PLL settings.

**Comment by informer2016** [comment]
@shkolnick-kun Thank you for reply! By the way, please could you confirm that BuguRTOS is 100% open source? Or there are some hidden closed source binaries [or magic numbers?](https://en.wikipedia.org/wiki/Magic_number_(programming)) for some boards

**Comment by informer2016** [comment]
@shkolnick-kun Please tell, STM32F767 does not require those non free libs? Also, from your list

    AVR/GCC - Arduino(tm)-nano (Atmega328p);
    STM8L/SDCC - STM8L Discovery kit;
    Cortex(tm)-M0/GCC - STM32L051 Discovery kit;
    Cortex(tm)-M3/GCC - STM32L1 Discovery kit for SMT32L152;
    Cortex(tm)-M4/GCC - STM32F4 Discovery kit for SMT32F407;
    Cortex(tm)-M7/GCC - STM32 Nucleo-144 for STM32F767 high performance MCUs.

which of these boards require the non free libs? Or all these boards are fully functional without them

**Comment by shkolnick-kun** [comment]
Proprietery libs are used in STM8/IAR STM8/Raisonance ports, all other ports use free libs.

**Comment by shkolnick-kun** [comment]
Feel free to reopen this on additional questions!
